# Generated by Django 2.2.5 on 2019-10-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
