# Generated by Django 2.2.5 on 2019-10-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20191005_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
