# Generated by Django 2.2.5 on 2019-10-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20191005_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rollnumber',
        ),
    ]
