# Generated by Django 2.2.5 on 2019-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paid_price',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=7),
            preserve_default=False,
        ),
    ]
