# Generated by Django 2.2.5 on 2019-10-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_rollnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='paid_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rollnumber',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
