# Generated by Django 2.2.5 on 2019-10-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20191016_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rollnumber',
            field=models.IntegerField(default=0),
        ),
    ]
